# Generated by Django 5.1.4 on 2024-12-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('ra', models.CharField(max_length=20)),
                ('data_nascimento', models.DateField()),
                ('cpf', models.CharField(max_length=14)),
                ('curso', models.CharField(max_length=100)),
                ('ano_fabricacao', models.IntegerField()),
                ('endereco', models.TextField()),
                ('imagem', models.ImageField(upload_to='images/')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
            ],
        ),
    ]
